
#multi-nomial Naieve bayes
#

#### Setup

In [1]:
%pip install scikit-learn pandas numpy matplotlib

Note: you may need to restart the kernel to use updated packages.


In [2]:
import os
os.chdir('../')

In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB, ComplementNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

#### Get data and Split into train test

In [ ]:
#import and combine cluster data with preprocessed data
cluster_data = pd.read_csv(r'Data\Seattle_Building_Clusters.csv')
preprocessed_data = pd.read_csv(r'Data\Building_Data_Preprocessed.csv')

preprocessed_data = preprocessed_data.assign(GHGIntensityCluster = cluster_data['GHGIntensityCluster']) #move clusters to preprocessed data

preprocessed_data = preprocessed_data.drop('BuildingName', axis = 1) #drop string columns
preprocessed_data = preprocessed_data.drop('Address', axis = 1)
preprocessed_data = preprocessed_data.drop('Latitude', axis = 1) #Drop columns with negative values
preprocessed_data = preprocessed_data.drop('Longitude', axis = 1)#Drop columns with negative values


preprocessed_data = preprocessed_data.dropna()


X = preprocessed_data.drop('GHGIntensityCluster', axis=1)
y = preprocessed_data['GHGIntensityCluster']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


#### Multi-nomial Naive Bayes

In [25]:
mnnb = MultinomialNB()

# Train the classifier
mnnb.fit(X_train, y_train)

# Make predictions
y_pred = mnnb.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Multinomial Naive Bayes Accuracy: {accuracy:.2f}')

print('Multinomial Classification Report:')
print(classification_report(y_test, y_pred))

print('Multinomial Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))


Multinomial Naive Bayes Accuracy: 0.49
Multinomial Classification Report:
              precision    recall  f1-score   support

           0       0.59      0.75      0.66       399
           1       0.27      0.40      0.32        81
           2       0.29      0.02      0.03       121
           3       0.30      0.22      0.26       143

    accuracy                           0.49       744
   macro avg       0.36      0.35      0.32       744
weighted avg       0.45      0.49      0.44       744

Multinomial Confusion Matrix:
[[301  42   4  52]
 [ 46  32   1   2]
 [ 71  29   2  19]
 [ 94  17   0  32]]


#### Complement Naive Bayes Classification

In [26]:
conb = ComplementNB()

# Train
conb.fit(X_train, y_train)

# Predict
y_pred = mnnb.predict(X_test)

# Evaluate
accuracy = accuracy_score(y_test, y_pred)
print(f'Compliment Naive Bayes Accuracy: {accuracy:.2f}')

print('Compliment Classification Report:')
print(classification_report(y_test, y_pred))

print('Compliment Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))



Compliment Naive Bayes Accuracy: 0.49
Compliment Classification Report:
              precision    recall  f1-score   support

           0       0.59      0.75      0.66       399
           1       0.27      0.40      0.32        81
           2       0.29      0.02      0.03       121
           3       0.30      0.22      0.26       143

    accuracy                           0.49       744
   macro avg       0.36      0.35      0.32       744
weighted avg       0.45      0.49      0.44       744

Compliment Confusion Matrix:
[[301  42   4  52]
 [ 46  32   1   2]
 [ 71  29   2  19]
 [ 94  17   0  32]]
